services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=essence_haven
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: essence_haven
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  db_data:
